# flux create helmrelease msr --chart msr-repo --source HelmRepository/msr-repo --chart-version 1.1.8 --namespace msr --depends-on rethinkdb-operator-helm-release,msr-operator-helm-release --export
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: msr
  namespace: msr
spec:
  chart:
    spec:
      chart: msr-repo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: msr-repo
      version: 1.1.8
  interval: 1m0s
