apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: rethinkdb-operator
  namespace: flux-system
spec:
  interval: 30m
  url: https://registry.mirantis.com/charts/rethinkdb/rethinkdb-operator
