apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres-operator
bases:
  - ../../base/postgres-operator
configMapGenerator:
  - name: postgres-operator-values
    files:
      - values.yaml=values.yaml
patchesStrategicMerge:
  - helmrelease.yaml