apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rethinkdb-operator
spec:
  chart:
    spec:
      chart: rethinkdb-operator
      sourceRef:
        kind: HelmRepository
        name: rethinkdb-operator
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: rethinkdb-operator-values
      valuesKey: values.yaml
      optional: true
  interval: 1h
  releaseName: rethinkdb-operator
  targetNamespace: rethinkdb-operator
  install:
    disableWait: true
  upgrade:
    disableWait: true
