apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
spec:
  chart:
    spec:
      chart: postgres-operator
      sourceRef:
        kind: HelmRepository
        name: postgres-operator
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: postgres-operator-values
      valuesKey: values.yaml
      optional: true
  interval: 1h
  releaseName: postgres-operator
  targetNamespace: postgres-operator
